<?php

namespace ContainerMml0OH6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NlymG4CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nlymG4C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nlymG4C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BookController::findAllBook' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HighScoreController::findAllBitcoins' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HighScoreController::findAllHighscore' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HistogramController::createHistogram' => ['privates', '.service_locator.OMjvgkg', 'get_ServiceLocator_OMjvgkgService', true],
            'App\\Controller\\HistogramController::findHistogram' => ['privates', '.service_locator.7x4zl0o', 'get_ServiceLocator_7x4zl0oService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BookController:findAllBook' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HighScoreController:findAllBitcoins' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HighScoreController:findAllHighscore' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\HistogramController:createHistogram' => ['privates', '.service_locator.OMjvgkg', 'get_ServiceLocator_OMjvgkgService', true],
            'App\\Controller\\HistogramController:findHistogram' => ['privates', '.service_locator.7x4zl0o', 'get_ServiceLocator_7x4zl0oService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BookController::findAllBook' => '?',
            'App\\Controller\\HighScoreController::findAllBitcoins' => '?',
            'App\\Controller\\HighScoreController::findAllHighscore' => '?',
            'App\\Controller\\HistogramController::createHistogram' => '?',
            'App\\Controller\\HistogramController::findHistogram' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BookController:findAllBook' => '?',
            'App\\Controller\\HighScoreController:findAllBitcoins' => '?',
            'App\\Controller\\HighScoreController:findAllHighscore' => '?',
            'App\\Controller\\HistogramController:createHistogram' => '?',
            'App\\Controller\\HistogramController:findHistogram' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
