<?php

namespace ContainerMml0OH6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7x4zl0oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7x4zl0o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7x4zl0o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['privates', '.errored.SDG8Hh5', NULL, 'Cannot determine controller argument for "App\\Controller\\HistogramController::findHistogram()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
        ]);
    }
}
