<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5BWnxTy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5BWnxTy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5BWnxTy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5BWnxTy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5BWnxTy\App_KernelDevDebugContainer([
    'container.build_hash' => '5BWnxTy',
    'container.build_id' => 'bc625d87',
    'container.build_time' => 1622042743,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5BWnxTy');
