<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFsAgqhd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFsAgqhd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFsAgqhd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFsAgqhd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFsAgqhd\App_KernelDevDebugContainer([
    'container.build_hash' => 'FsAgqhd',
    'container.build_id' => '59223539',
    'container.build_time' => 1621929881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFsAgqhd');
