<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY2bOEQS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY2bOEQS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY2bOEQS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY2bOEQS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY2bOEQS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y2bOEQS',
    'container.build_id' => 'e3c4aad6',
    'container.build_time' => 1621587965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY2bOEQS');
